// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";

export let options = {
  maxRedirects: 4,
  stages: [
    { duration: '0.25m', target: 1 },    // start at 1 user
    { duration: '0.25m', target: 5 },    // stay at 5 users for 15 seconds
    { duration: '0.25m', target: 10 },   // ramp-up to 5 users
    { duration: '0.25m', target: 0 },    // go-down to 0 users
  ],
  thresholds: {
    http_req_duration: ['p(95)<100'], // 95% of requests should be below 100ms
  },
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "Weather API",
    id: "46a735ca-3950-4fc3-abf0-e1855cb1cf84",
    method: "GET",
    address: "https://api.data.gov.sg/v1/environment/24-hour-weather-forecast",
    post(response) {
      pm.test("should return status code 200", function() {
        pm.response.to.be.success;
      });

      pm.test("should return items", function() {
        const responseData = pm.response.json();
        pm.expect(responseData).to.have.property("items");
        pm.expect(responseData.items.length).to.be.greaterThan(0);
      });
    }
  });
}
